name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: 20


    - name: Deploy to server
      run: |
        git config --global user.email "iamshashankpal398@gmail.com"
        git config --global user.name "depgod"
        git pull https://github.com/depgod/scywhy.git main
        /bin/systemctl reload php8.3-fpm.service
        sleep 5
        /bin/systemctl reload nginx.service
        sleep 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
